sudo: required

services:
    - docker

env:
    - VERSION=8 DIRECTORY=8 ALIAS=latest
    - VERSION=8-node DIRECTORY=8/node ALIAS=fpm
    - VERSION=8-fpm DIRECTORY=8/fpm ALIAS=node
    - VERSION=8-fpm-node DIRECTORY=8/fpm/node ALIAS=fpm-node

before_script:
    - docker pull squareweave/dockerized-drupal-composer:$VERSION

script:
    - docker build --pull -t squareweave/dockerized-drupal-composer:$VERSION $DIRECTORY

after_success:
    - docker tag squareweave/dockerized-drupal-composer:$VERSION squareweave/dockerized-drupal-composer:$ALIAS
    - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
    - provider: script
      script: docker push squareweave/dockerized-drupal-composer:$VERSION
      on:
          branch: master

    - provider: script
      script: docker push squareweave/dockerized-drupal-composer:$ALIAS
      on:
          branch: master
